# Generated by Django 3.2.4 on 2021-08-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_package_postdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='postdate',
        ),
        migrations.AddField(
            model_name='package',
            name='endtime',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
