# Generated by Django 3.2.4 on 2021-08-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20210812_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('booking', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(default=3, upload_to=''),
            preserve_default=False,
        ),
    ]
